article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addarticle,name = "addarticle"),
    path('article/<int:id>',views.detail,name = "detail"),
    path('uptade/<int:id>',views.uptadeArticle,name = "uptade"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('',views.articles,name = "articles"),
    path('comment/<int:id>',views.addComment,name = "comment"),
]

batublog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name = "index"),
    path('about/', views.about,name = "about"),
    path('articles/', include("article.urls")),
    path('user/', include("user.urls")),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django_email_verification import urls as mail_urls
app_name = "user"

urlpatterns = [
    
    path('register/',views.register,name = "register"),
    path('login/',views.loginUser,name = "login"),
    path('logout/',views.logoutUser,name = "logout"),
    path('termscon/',views.Terms,name = "termscon"),
    path('email/', include(mail_urls)),
    path('confirm/',views.confirm,name = "confirm"),
    path('success/',views.success,name = "success"),

]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name = "Yazar")
    title = models.CharField(max_length = 50,verbose_name = "Başlık")
    content = RichTextField("İçerik")
    created_date = models.DateTimeField(auto_now_add=True,verbose_name = "Oluşturulma Tarihi")
    article_image = models.FileField(blank = True,null = True,verbose_name = "Makaleye Fotograf Ekleyin.")
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']
class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE,verbose_name = "Makale",related_name = "comments")
    comment_author = models.CharField(max_length = 50,verbose_name = "İsim")
    comment_content = models.CharField(max_length = 200,verbose_name = "Yorum")
    comment_date = models.DateTimeField(auto_now_add=True,verbose_name = "Yorum Tarihi")
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):

    class Meta:

        model = Article
        fields = ["title","content","article_image"]
        

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForm
from django.contrib import messages
from .models import Article,Comment
from django.contrib.auth.decorators import login_required
# Create your views here.


def articles(request):
   

    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})


    articles = Article.objects.all()
    

    return render(request,"articles.html",{"articles":articles})

def index(request):
    return render(request,"index.html")

def about(request):
    return render(request,"about.html")

@login_required(login_url = "user:login")
def dashboard(request):

    articles = Article.objects.filter(author = request.user)

    context = {
        "articles":articles
    }
    
    return render(request,"dashboard.html",context)


@login_required(login_url = "user:login")
def addarticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)

    if form.is_valid():

        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"Makale Başarıyla Oluşturuldu.")
        return redirect("index")
    context = {
        "form":form
    }

    return render(request,"addarticle.html",context)

def detail(request,id):
    #article = Article.objects.filter(id = id).first()

    article = get_object_or_404(Article,id = id)
    comments = article.comments.all()

    
    return render(request,"detail.html",{"article":article,"comments":comments})

@login_required(login_url = "user:login")
def uptadeArticle(request,id):

    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance = article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"Makale Başarıyla Güncellendi.")
        return redirect("index")

    context = {
        "form":form
    }


    return render(request,"uptade.html",context)


@login_required(login_url = "user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)

    article.delete()
    messages.success(request,"Makale Başarıyla Silindi.")
    return redirect("article:dashboard")

def addComment(request,id):
    article = get_object_or_404(Article,id = id)

    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author = comment_author,comment_content = comment_content)

        newComment.article = article

        newComment.save()

    return redirect(reverse("article:detail",kwargs={"id":id}))

templates/about.html
{% extends "layout.html" %}
<head>
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>



{% block body %}
<style>
	.paddingTB60 {padding:60px 0px 60px 0px;}
	.gray-bg {background: #F1F1F1 !important;}
	.about-title {}
	.about-title h1 {color: #535353; font-size:45px;font-weight:600;}
	.about-title span {color: #AF0808; font-size:45px;font-weight:700;}
	.about-title h3 {color: #535353; font-size:23px;margin-bottom:24px;}
	.about-title p {color: #7a7a7a;line-height: 1.8;margin: 0 0 15px;}
	.about-paddingB {padding-bottom: 12px;}
	.about-img {padding-left: 57px;}
	
	/* Social Icons */
	.col-lg-8{
		display: table-cell;
		vertical-align: middle;
		text-align: center;

		
	}
	.about-icons {margin:48px 0px 48px 0px ;}
	.about-icons i{margin-right: 10px;padding: 0px; font-size:35px;color:#323232;box-shadow: 0 0 3px rgba(0, 0, 0, .2);}
	.about-icons li {margin:0px;padding:0;display:inline-block;}
	#social-fb:hover {color: #3B5998;transition:all .001s;}
	 #social-tw:hover {color: #4099FF;transition:all .001s;}
	 #social-gp:hover {color: #d34836;transition:all .001s;}
	 #social-em:hover {color: #f39c12;transition:all .001s;}
	</style>

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

            <div class="col-lg-8">
                <h1>Hakkımızda</h1>
				<hr>
				<p>
					Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi illo incidunt quae. Sequi aliquid, corrupti suscipit totam quam, possimus est consequatur veritatis distinctio, rem in fuga sit. Aperiam, maiores deleniti!lor
					Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quo libero deleniti perferendis! Dignissimos accusamus excepturi quae culpa, illum expedita ut qui quasi sapiente non rerum temporibus magni, earum deserunt? Quos.
					Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odit in maiores quia veritatis corporis recusandae unde, qui nemo assumenda consequuntur! Explicabo molestiae quod asperiores nemo totam recusandae repellendus doloremque ad?
					Lorem ipsum dolor, sit amet consectetur adipisicing elit. Delectus dolore sequi et tenetur totam velit animi placeat ipsam, consectetur omnis, facere reprehenderit sunt necessitatibus ratione autem modi, ipsa nisi distinctio!
					Lorem, ipsum dolor sit amet consectetur adipisicing elit. Culpa tempore corporis iure ea. Ducimus recusandae quae illo? Dicta doloremque molestiae quas rem soluta ut, iure labore dolorum autem optio in?
					Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis laudantium veniam enim dignissimos et qui molestiae, voluptates, accusantium at doloribus nostrum provident aperiam rerum aliquam. Odit fugit natus repellat accusamus.
					Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci animi nulla dolorum mollitia dolor, qui, quae quos illo perspiciatis maiores molestias labore quis eum voluptas, sit iusto amet libero quia.
					Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laboriosam earum ad rem sit animi ducimus! Vel ex iure qui, aperiam veniam corrupti nesciunt dignissimos fugiat accusamus dolor architecto, corporis accusantium!
					Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veniam perspiciatis optio doloribus reiciendis dolore rerum facere aut totam quod! Veritatis vero velit illum, vel sint aut odit quos quasi nemo!
				</p>
				
				<footer>
				<div class="about-icons" > 
					<h1>İletişim</h1>
					<hr>
					<ul>
						<li><a href="https://www.facebook.com/"><i id="social-fb" class="fa fa-facebook-square fa-3x social" ></i></a> </li>
						<li><a href="https://twitter.com/batuhannbagg"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a> </li>
						<li> <a href="https://mail.google.com/"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a> </li>
						<li> <a href="mailto:batuhannbagg@gmail.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a> </li>
						<li> <a href="https://github.com/batuhanbag"><i id="social-em" class="fab fa-github-square"></i></a> </li>
						


					</ul>
				</div>
				</footer>
            </div>
        </div>
</div>

		







<!-- {% comment %} <div class="about-section paddingTB60 gray-bg">
                <div class="container">
                    <div class="row">
						<div class="col-md-7 col-sm-6">
							<div class="about-title clearfix">
								<h1>About <span>Appmom</span></h1>
								<h3>Lorem ipsum dolor sit amet </h3>
								<p class="about-paddingB">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet dolor libero, eget venenatis mauris finibus dictum. Vestibulum quis elit eget neque porttitor congue non sit amet dolor. Proin pretium purus a lorem ornare </p>
								<p>sed lobortis pulvinar. Integer laoreet mi id eros porta euismod. Suspendisse potenti. Nulla eros mauris, convallis et sem tempus, viverra hendrerit sapien</p>
						<div class="about-icons"> 
                            <ul >
                                <li><a href="https://www.facebook.com/"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a> </li>
                                <li><a href="https://twitter.com/"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a> </li>
                                <li> <a href="https://plus.google.com/"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a> </li>
                                <li> <a href="mailto:bootsnipp@gmail.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a> </li>
                            </ul>       
               
               
	           
	           
	        
	        </div>
							</div>
						</div>
						<div class="col-md-5 col-sm-6">
							<div class="about-img">
								<img src="https://devitems.com/preview/appmom/img/mobile/2.png" alt="">
							</div>
						</div>	
                    </div>
                </div>
            </div> {% endcomment %} -->







{% endblock body %}

templates/addarticle.html
{% extends 'layout.html' %}


{% block body %}

{% load crispy_forms_tags %}



<div class="row">
  <div class="col-md-6 offset-md-3">
  <h3>Makale Oluştur</h3>
  <hr>
  <form method="post" enctype="multipart/form-data">

    {% csrf_token %}

    {{form.media}}
    
    {{form|crispy}}
    <br>
    <button type = "submit" class = "btn btn-danger float-right">Ekle</button>


{% endblock body %}

templates/articles.html
{% extends "layout.html" %}



{% block body %}

<style>

#hata{
    margin: auto;
}

</style>


<div class = "row">
        <div class="col-md-10 offset-md-3">
            <div class="col-lg-8">
                <h3>Makaleler</h3>
                <hr>
            </div>
        </div>
</div>

<div class ="row">
    <div class="col-md-10 offset-md-3">
            <div class="col-lg-8">
            
            <form class="form-inline my-2 my-lg-0">
                 {% csrf_token %} 
                <input class="form-control mr-sm-2" type="search" placeholder="Ara.." aria-label="Search" name = "keyword">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search-location"></i></button>
            
            </form>
            </div>
    </div>





{% if articles %}
{% for article in articles  %}

    <div class="row">
    <div class="col-md-10 offset-md-3">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <a href="{% url 'article:detail' article.id %}">
        <h2 class="mt-4">{{article.title}}</h2>
        </a>

        <!-- Author -->
        <p class="lead">
          
          <a href="#">{{article.author.username}}</a>  Tarafından yayınlandı.
        </p>

        <hr>

        <!-- Date/Time -->
        <p> Tarih: {{article.created_date}}</p>

        <hr>

        <!-- Preview Image -->
        {% comment %} <img class="img-fluid rounded" src="http://placehold.it/900x300" alt=""> {% endcomment %}

        

        <!-- Preview Image -->
        {% if article.article_image %}
        
        <a href="{% url 'article:detail' article.id %}">
        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
        </a>
        
        {% endif %}

        <!-- Post Content -->
        <p class = "lead">
            {{article.content|safe|truncatewords:30}}


            
            
        </p>
         <a  style = "float : right;" href="{%  url 'article:detail' article.id %}" class = "btn btn-danger">Devamını Oku</a>
        
      </div>

      
    </div>    
    </div>


{% endfor %}


{% else %}
<div class = "row">
        <div class="col-md-10 offset-md-3">
            <div class="col-lg-8">
            <div id = "hata" class = "alert alert-danger">

            Makale Bulunamadı

</div>
</div>
</div>
</div>
{% endif %}

{% endblock body %}

templates/confirm_template.html
{% extends "layout.html" %}

{% block body %}

<br>
<br>
<br>
<br>

<div class="jumbotron text-center">
  <h1 class="display-3">Kaydın Tamamlandı!</h1>
  <p class="lead"><strong>Giriş Yapabilirsin</strong></p>
  <hr>
  <p class="lead">
    <a class="btn btn-primary btn-sm" href="{% url 'user:login' %}" role="button">Giriş Yap</a>
  </p>
  <p>
    Bir sorun mu var ? <a href="">Bizimle İletişime Geç</a>
  </p>
  
</div>




{% endblock body %}

templates/dashboard.html
{% extends 'layout.html' %}


{% block body %}

<h3>Kontrol Paneli</h3>
<hr>

Hoşgeldin,<small>{{request.user.username}}</small>
<hr>

<a href="{% url 'article:addarticle' %}" class = "btn btn-danger"> Makale Ekle </a>

<hr>
{% if articles %}
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Başlık</th>
      <th scope="col">Yazar</th>
      <th scope="col">Tarih</th>
      <th scope="col"></th>
      <th scope="col">Güncelle</th>
      
      <th scope="col">Sil</th>
    </tr>
  </thead>
  <tbody>

    {% for article in articles %}
    <tr>
      <th scope="row">{{article.id}}</th>
      <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
      <td>{{article.author.username}}</td>
      <td>{{article.created_date}}<td>
      <td><a href="{% url 'article:uptade' article.id %}" class = "btn btn-success"><i class="fa fa-cog"></i> Güncelle</a></td>
      <td><a href="{% url 'article:delete' article.id %}" class = "btn btn-danger">Sil <i class="fas fa-trash-alt"></i></a></td>

    </tr>


    
    {% endfor %}
    {% comment %} <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr> {% endcomment %}
    
  </tbody>
</table>
{% else %}

<div class = "alert alert-danger">
    Henüz Bir Makaleniz Bulunamadı,Makale Oluşturmak İçin <a href="{% url 'article:addarticle' %}">Buraya Tıklayınız.</a>
</div>

{% endif %}

{% endblock body %}

templates/detail.html
{% extends 'layout.html' %}


{% block body %}

<div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h2 class="mt-4">{{article.title}}</h2>

        <!-- Author -->
        <p class="lead">
          Yazar:
          <a href="#">{{article.author.username}}</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p> Tarih: {{article.created_date}}</p>

        <hr>

        <!-- Preview Image -->
        {% comment %} <img class="img-fluid rounded" src="http://placehold.it/900x300" alt=""> {% endcomment %}

        

        <!-- Preview Image -->
        {% if article.article_image %}
        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
        
        {% endif %}

        <!-- Post Content -->
        <p class = "lead">
            {{article.content|safe}}
        </p>

        <h4>Yorumlar</h4>
        <hr>
        {% if comments %}
        
        {% for comment in comments %}
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="https://muratselek.com.tr/wp-content/uploads/2019/01/yorum-icon-avatar-men-50x50.png" alt="">

          <div class="media-body">
            <h5 class="mt-0">{{comment.comment_author}}</h5>
            {{comment.comment_date}} <br>
            {{comment.comment_content}}
          </div>
        </div>
        
        {% endfor %}
        
        {% else %}
        <div class = "alert alert-danger">Bu makaleye yorum yapılmamıştır.İlk yorumu yapan siz olun!</div>
        {% endif %}


        <div class="card my-4">
          <h5 class="card-header">Yorum Ekle:</h5>
          <div class="form-group">
            
          </div>
            <form action = "{% url 'article:comment'  article.id %}" method = "post">
              {% csrf_token %}
            <div class = "form-group"></div>
              <input  name = "comment_author" type="text"   class="form-control" id="formGroupExampleInput" placeholder = "İsiminizi Giriniz">
              
              <br>
              <label for="formGroupExampleInput"></label>
            
              <div class="form-group">
                <textarea name = "comment_content" class="form-control" rows="5" placeholder = "Yorumunuzu Ekleyiniz"></textarea>
                
              </div>
              <button type="submit" class="btn btn-danger"  style = "float : right;">Ekle</button>
            </form>
          </div>
        </div>
      </div>

     
        
    </div>

    
{% endblock body %}

templates/index.html
{% extends "layout.html" %}

{% block body %}

<div class = "jumbotron text-center">

    <h3>Batuhan Bag Bloguna Hoşgeldiniz</h3>
    <p> Blogumuza kayıt olup yazar olarak kendi yazılarınızı makalelerinizi paylaşıp insanlara yardımcı olabilirsiniz..<p>
</div>

<p>

    {% if request.user.is_authenticated %}
        Giriş Yapılmış,{{request.user.username}}
    
    {% else %}
        Giriş Yapılmamış.
    {% endif %}
</p>

{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
    <style>
        
        
    </style>
    
    <title>BatuBLOG</title>
    
</head>
<body>  
        {% include "includes/navbar.html" %}

        

        <div style = "margin-top : 100px; margin-bottom:100px;" class = "container">
            
                
            {% if messages %}
                
                    {% for message in messages %}
                    {% if message.tags == "info" %}
                    <div class="alert alert-danger">{{ message }}</div>
                    {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>

                    {% endif %}


                    {% endfor %}
                
                {% endif %}
           
            {% block body %}
            
            {% endblock body %}
        
        <!-- <div id="altfooter" align = "center"><a href="#"><strong>Copyright © 2020 Tüm Hakları BB Saklıdır.</strong></a></div> -->
        </div>
    

      <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js'%}"></script>
      <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
      <script src="{% static 'js/sidebar.js' %}"></script>
      
    </body>
   
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}



<div class="row">
  <div class="col-md-6 offset-md-3">
  <h3>Giriş Yap</h3>
  <hr>
  <form method = "post">

    {% csrf_token %}

    {{form|crispy}}
    <a href="{% url 'user:register' %}">Hesabınız Yokmu Hemen Kayıt Olun!</a>
    <br>
    <button type = "submit" class = "btn btn-danger float-right">Giriş Yap</button>
</form>
  
  
  
  </div>
</div>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}





<div class="row">
  <div class="col-md-6 offset-md-3">
  <h3>Kayıt Ol</h3>
  <hr>
  <form method = "post">

    {% csrf_token %}

    {{form|crispy}}

    <input type="checkbox" name="tech" id="tech" >
    <a  target = _blank href="{% url 'user:termscon' %}">Kullanım Sözleşmesi</a>'ni Okudum Kabul Ediyorum.
    <br>
    <br>
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <div class="g-recaptcha" data-sitekey="6LfKmyoaAAAAAGvr7OY_H7ifFA04GKO5KNXZMvG0"></div>
    <br>
    <button  type = "submit" class = "btn btn-danger float-right">Kayıt Ol</button>
</form>
  
  
  
  </div>
</div>

   
   
{% endblock body %}

templates/success.html
{% extends "layout.html" %}

{% block body %}

<br>
<br>
<br>
<br>

<div class="jumbotron text-center">
  <h1 class="display-3">Teşekkür Ederiz!</h1>
  <p class="lead"><strong>E-posta adresine gelen</strong> mail ile hesabını doğrulayabilirsin.</p>
  <hr>
  <p class="lead">
    <a class="btn btn-primary btn-sm" href="{% url 'index' %}" role="button">Anasayfaya Dön</a>
  </p>

  <p>
    Bir sorun mu var? <a href="">Bizimle İletişime Geç</a>
  </p>
  
</div>




{% endblock body %}

templates/terms.html
{% extends "layout.html" %}



{% block body %}


<h3>Kullanım Şartları</h3>
<hr>
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae incidunt aspernatur iusto exercitationem quaerat, accusantium modi ab distinctio obcaecati cupiditate culpa commodi sunt iste assumenda numquam, illum dolorum aliquid harum!
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae incidunt aspernatur iusto exercitationem quaerat, accusantium modi ab distinctio obcaecati cupiditate culpa commodi sunt iste assumenda numquam, illum dolorum aliquid harum!
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae incidunt aspernatur iusto exercitationem quaerat, accusantium modi ab distinctio obcaecati cupiditate culpa commodi sunt iste assumenda numquam, illum dolorum aliquid harum!
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae incidunt aspernatur iusto exercitationem quaerat, accusantium modi ab distinctio obcaecati cupiditate culpa commodi sunt iste assumenda numquam, illum dolorum aliquid harum!
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae incidunt aspernatur iusto exercitationem quaerat, accusantium modi ab distinctio obcaecati cupiditate culpa commodi sunt iste assumenda numquam, illum dolorum aliquid harum!
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae incidunt aspernatur iusto exercitationem quaerat, accusantium modi ab distinctio obcaecati cupiditate culpa commodi sunt iste assumenda numquam, illum dolorum aliquid harum!
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae incidunt aspernatur iusto exercitationem quaerat, accusantium modi ab distinctio obcaecati cupiditate culpa commodi sunt iste assumenda numquam, illum dolorum aliquid harum!
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae incidunt aspernatur iusto exercitationem quaerat, accusantium modi ab distinctio obcaecati cupiditate culpa commodi sunt iste assumenda numquam, illum dolorum aliquid harum!
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae incidunt aspernatur iusto exercitationem quaerat, accusantium modi ab distinctio obcaecati cupiditate culpa commodi sunt iste assumenda numquam, illum dolorum aliquid harum!
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae incidunt aspernatur iusto exercitationem quaerat, accusantium modi ab distinctio obcaecati cupiditate culpa commodi sunt iste assumenda numquam, illum dolorum aliquid harum!
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae incidunt aspernatur iusto exercitationem quaerat, accusantium modi ab distinctio obcaecati cupiditate culpa commodi sunt iste assumenda numquam, illum dolorum aliquid harum!
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae incidunt aspernatur iusto exercitationem quaerat, accusantium modi ab distinctio obcaecati cupiditate culpa commodi sunt iste assumenda numquam, illum dolorum aliquid harum!
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae incidunt aspernatur iusto exercitationem quaerat, accusantium modi ab distinctio obcaecati cupiditate culpa commodi sunt iste assumenda numquam, illum dolorum aliquid harum!



{% endblock body %}

templates/uptade.html
{% extends 'layout.html' %}


{% block body %}

{% load crispy_forms_tags %}



<div class="row">
  <div class="col-md-6 offset-md-3">
  <h3>Makale Güncelle</h3>
  <hr>
  <form method="post" enctype="multipart/form-data">

    {% csrf_token %}

    {{form.media}}
    
    {{form|crispy}}
    <br>
    <button type = "submit" class = "btn btn-danger float-right">Makale Güncelle</button>


{% endblock body %}